/* generated by dia/codegen.py */
class Cilindro 
{
public:
	Cilindro (double radio,
	          double altura);
	double getRadio ();
	double getAltura ();
	 setRadio (double radio);
	 setAltura (double altura);
	double getSuperficie ();
	double getVolumen ();
private:
	double radio;
	double altura;
};

